apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
    external_labels:
      monitor: 'global-monitor'

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus:9090']
        tls_config:
          insecure_skip_verify: true
      - job_name: 'node'
        scrape_interval: 50s
        scrape_timeout:  5s
        honor_labels: true
        metrics_path: '/federate'
        params:
          'match[]':
            - '{job="prometheus"}'
            - '{__name__=~"job:.*"}'
            - '{job="kubernetes-nodes"}'
            - '{job="kubernetes-cadvisor"}'
            # - '{name=~".+"}'
            - '{job="kubernetes-service-endpoints"}'
            # - '{job="kubernetes-pods"}'
            # - '{job="kubernetes-apiservers"}'
            # - '{pod_name=".+"}'
            # - '{namespace="kube-system"}'
            # - '{job="node-exporter"}'
        static_configs:
          - targets:
            - '192.168.9.10:9090'
            labels:
              clusterID: Cluster1
          - targets:
            - '192.168.9.20:9090'
            labels:
              clusterID: Cluster2
          - targets:
            - '192.168.9.30:9090'
            labels:
              clusterID: Cluster3
          - targets:
            - '192.168.9.40:9090'
            labels:
              clusterID: Cluster4
          - targets:
            - '192.168.9.50:9090'
            labels:
              clusterID: Cluster5
          - targets:
            - '192.168.9.60:9090'
            labels:
              clusterID: Cluster6
          - targets:
            - '192.168.9.65:9090'
            labels:
              clusterID: Cluster7

      # - job_name: 'node-exporter'
      #   static_configs:
      #     - targets: ['node-exporter:9100']
      # - job_name: 'cAdvisor'
      #   static_configs:
      #     - targets: ['cadvisor:8080']