version: '3'
services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.7
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - $PWD/influxdb:/var/lib/influxdb
    environment: 
      - INFLUXDB_DB=influxdb_central
      - INFLUXDB_USER=fogguru
      - INFLUXDB_USER_PASSWORD=fogguru
    restart: unless-stopped

  chronograf:
    image: chronograf:1.8
    volumes:
      - $PWD/chronograf/data/:/var/lib/chronograf/
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - $PWD/grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    user: root
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    ports:
      - '9090:9090'

  # node-exporter:
  #   image: prom/node-exporter
  #   ports:
  #     - '9100:9100'

  # cadvisor:
  #   image: google/cadvisor:latest
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   ports:
  #     - '8080:8080'