apiVersion: v1
kind: Service
metadata:
  name: nodered
  labels:
    app: nodered
spec:
  type: NodePort
  ports:
    - port: $port
      targetPort: $port
  selector:
    app: nodered
  externalIPs:
  - $myclusterIP
