apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |-
    # Ip/hostname to listen to.
    # If not given, will listen on all interfaces
    #bind_address

    # Port to use for the default listener.
    port 1883

    # Allow anonymous users to connect?
    # If not, the password file should be created
    allow_anonymous true

    # if allow_anonymous is false, we should use password file to authenticate
    password_file /mosquitto/config/password_file.txt
  password_file.txt: |-
    fogguru:FogGuru2020
    user:user