apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  type: NodePort
#  clusterIP: None
  ports:
    - port: 1883
      targetPort: 1883
  selector:
    app: mosquitto
  #externalIPs:
  # - 192.168.0.175