kind: PersistentVolume
apiVersion: v1
metadata:
  name: mosquitto-pv-volume
  labels:
    type: local
    app: mosquitto
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/picocluster/chirpstack/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto
  labels:
    app: mosquitto	
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
