kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: $varnamespace
  name: team-admin
rules:
- apiGroups: ["","apps"]
  resources: ["pods","pods/log", "pods/portforward", 
              "deployments", "deployments/logs",
              "services", "services/logs"
              ]
  verbs: ["create","get", "list", "watch", "delete"]
