global:
  scrape_interval: 1s
  external_labels:
    monitor: 'global-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'federate'
    scrape_interval: 5s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="prometheus"}'
        - '{__name__=~"job:.*"}'
        - '{job="kubernetes-nodes"}'
        - '{job="kubernetes-cadvisor"}'
        # - '{name=~".+"}'
        # - '{job="kubernetes-service-endpoints"}'
        # - '{job="kubernetes-pods"}'
        # - '{job="kubernetes-apiservers"}'
        # - '{pod_name=".+"}'
        # - '{namespace="global"}'
        - '{job="node-exporter"}'
    static_configs:
      - targets:
        - '192.168.9.65:9090'
        #- 'source-prometheus-2:9090'
        #- 'source-prometheus-3:9090'

  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  # - job_name: 'cAdvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']