apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chirpstack-application-server
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
  labels:
    app: chirpstack-application-server
