apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx
  labels:
    app: influx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influx
  template:
    metadata:
      labels:
        app: influx
    spec:
      containers:
        - image: influxdb:1.8.3
          name: influx
          ports:
            - containerPort: 8086
              name: influx
          env:
            - name: INFLUXDB_ADMIN_USER
              value: admin
            - name: INFLUXDB_ADMIN_PASSWORD
              value: admin
            # - name: INFLUXDB_HTTP_AUTH_ENABLED
            #   value: 'true'
          #   - name: INFLUXDB_DB
          #     value: chirpstack_as
          #   - name: INFLUXDB_USER
          #     value: fogguru
          #   - name: INFLUXDB_USER_PASSWORD
          #     value: FogGuru2020
          volumeMounts:
            - name: influx-pv
              mountPath: /var/lib/influxdb
            - name: influxdb-config
              mountPath: /etc/influxdb/influxdb.conf
              subPath: influxdb.conf
      volumes:
        - name: influx-pv
          persistentVolumeClaim:
            claimName: influx-pv-claim
        - name: influxdb-config
          configMap:
            name: influxdb-config