kind: PersistentVolume
apiVersion: v1
metadata:
  name: influx-pv-volume
  labels:
    app: influx
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: influxdb-gluster
    path: /influxdb_volume
    readOnly: false      
  persistentVolumeReclaimPolicy: Retain

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influx-pv-claim
  labels:
    app: influx
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi